language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run build

deploy:
  provider: heroku
  skip_cleanup: true
  keep_history: true
  api-key:
    secure: $HEROKU_API_KEY
  app: accuweather-client
  local_dir: build
  on: master
